create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  category varchar(255) not null,
  price numeric(10, 2) not null,
  image_url varchar(500),
  description varchar(2000),
  constraint products_category_check check (category in ('GPU', 'CPU', 'RAM', 'SSD', 'Fonte')),
  constraint products_price_check check (price >= 0.01)
);

create index if not exists products_id_desc_idx on public.products (id desc);

create table if not exists public.customer_accounts (
  id bigint generated by default as identity primary key,
  username varchar(40) not null,
  password_hash varchar(100) not null,
  created_at timestamptz not null default now()
);

create unique index if not exists customer_accounts_username_lower_unique
  on public.customer_accounts (lower(username));

create table if not exists public.purchase_orders (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customer_accounts(id),
  full_name varchar(160) not null,
  email varchar(254) not null,
  cpf varchar(11) not null,
  payment_method varchar(30) not null,
  total numeric(12, 2) not null check (total >= 0),
  status varchar(30) not null default 'RECEBIDO',
  created_at timestamptz not null default now()
);

create index if not exists purchase_orders_customer_created_at_idx
  on public.purchase_orders (customer_id, created_at desc);

create table if not exists public.purchase_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.purchase_orders(id) on delete cascade,
  product_id bigint,
  product_name varchar(180) not null,
  quantity integer not null check (quantity between 1 and 99),
  unit_price numeric(12, 2) not null check (unit_price >= 0)
);
