create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  category varchar(255) not null,
  price numeric(10, 2) not null,
  image_url varchar(500),
  description varchar(2000),
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  version bigint not null default 0,
  constraint products_price_check check (price >= 0.01)
);

create index if not exists products_id_desc_idx on public.products (id desc);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  content_type varchar(16) not null,
  byte_size integer not null,
  image_base64 varchar(2800000) not null,
  sort_order integer not null,
  created_at timestamptz not null default now(),
  constraint product_images_content_type_check
    check (content_type in ('image/jpeg', 'image/png', 'image/webp')),
  constraint product_images_byte_size_check check (byte_size between 1 and 2097152),
  constraint product_images_sort_order_check check (sort_order between 0 and 7),
  constraint product_images_position_unique unique (product_id, sort_order)
);

create index if not exists product_images_product_order_idx
  on public.product_images (product_id, sort_order);

create table if not exists public.storefront_hero_settings (
  id integer primary key default 1,
  mode varchar(16) not null default 'PRODUCTS',
  interval_seconds integer not null default 5,
  version bigint not null default 0,
  constraint storefront_hero_settings_singleton_check check (id = 1),
  constraint storefront_hero_settings_mode_check check (mode in ('MANUAL', 'PRODUCTS')),
  constraint storefront_hero_settings_interval_check check (interval_seconds between 3 and 30)
);

insert into public.storefront_hero_settings (id, mode, interval_seconds, version)
values (1, 'PRODUCTS', 5, 0)
on conflict (id) do nothing;

create table if not exists public.storefront_hero_images (
  id bigint generated by default as identity primary key,
  settings_id integer not null references public.storefront_hero_settings(id) on delete cascade,
  content_type varchar(16) not null,
  byte_size integer not null,
  image_base64 varchar(2800000) not null,
  alt_text varchar(160) not null,
  sort_order integer not null,
  created_at timestamptz not null default now(),
  constraint storefront_hero_images_content_type_check
    check (content_type in ('image/jpeg', 'image/png', 'image/webp')),
  constraint storefront_hero_images_byte_size_check check (byte_size between 1 and 2097152),
  -- 100..107 is reserved for the service's transactional two-phase reorder.
  constraint storefront_hero_images_sort_order_check
    check (sort_order between 0 and 7 or sort_order between 100 and 107),
  constraint storefront_hero_images_position_unique unique (settings_id, sort_order)
);

create index if not exists storefront_hero_images_settings_order_idx
  on public.storefront_hero_images (settings_id, sort_order);

create table if not exists public.customer_accounts (
  id bigint generated by default as identity primary key,
  username varchar(40) not null,
  password_hash varchar(100) not null,
  created_at timestamptz not null default now()
);

create unique index if not exists customer_accounts_username_lower_unique
  on public.customer_accounts (lower(username));

alter table public.customer_accounts add column if not exists full_name varchar(160);
alter table public.customer_accounts add column if not exists email varchar(254);
alter table public.customer_accounts add column if not exists cpf varchar(11);
alter table public.customer_accounts add column if not exists profile_updated_at timestamptz;

create table if not exists public.customer_addresses (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customer_accounts(id) on delete cascade,
  label varchar(60) not null,
  postal_code varchar(8) not null,
  state varchar(2) not null,
  city varchar(120) not null,
  neighborhood varchar(160) not null,
  street varchar(180) not null,
  address_number varchar(20) not null,
  complement varchar(120),
  is_default boolean not null default false,
  version bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint customer_addresses_postal_code_check check (postal_code ~ '^[0-9]{8}$'),
  constraint customer_addresses_state_check check (state ~ '^[A-Z]{2}$')
);

create index if not exists customer_addresses_customer_created_idx
  on public.customer_addresses (customer_id, created_at);
create unique index if not exists customer_addresses_one_default_unique
  on public.customer_addresses (customer_id) where is_default;

create table if not exists public.purchase_orders (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customer_accounts(id),
  full_name varchar(160) not null,
  email varchar(254) not null,
  cpf varchar(11) not null,
  payment_method varchar(30) not null,
  postal_code varchar(8),
  state varchar(2),
  city varchar(120),
  neighborhood varchar(160),
  street varchar(180),
  address_number varchar(20),
  complement varchar(120),
  total numeric(12, 2) not null check (total >= 0),
  status varchar(40) not null default 'PENDING_PAYMENT',
  payment_state varchar(30) not null default 'PENDING',
  refund_state varchar(20) not null default 'NONE',
  dispute_state varchar(20) not null default 'NONE',
  fulfillment_review_required boolean not null default false,
  inventory_status varchar(30) not null default 'NONE',
  payment_provider varchar(20) not null default 'STRIPE',
  legacy_payment_reference varchar(600),
  external_reference varchar(80) unique,
  checkout_session_id varchar(255) unique,
  checkout_status varchar(20),
  checkout_url varchar(2048),
  checkout_request_hash varchar(64),
  checkout_expires_at timestamptz,
  provider_success_url varchar(2048),
  provider_cancel_url varchar(2048),
  pix_expires_seconds bigint,
  boleto_expires_days bigint,
  payment_intent_id varchar(255) unique,
  captured_amount numeric(12, 2) check (captured_amount >= 0),
  captured_currency varchar(3),
  refunded_amount numeric(12, 2) not null default 0 check (refunded_amount >= 0),
  refund_attempt_id varchar(36),
  refund_attempt_amount numeric(12, 2)
    check (refund_attempt_amount > 0 and refund_attempt_amount <= total),
  gateway_refund_id varchar(255),
  payment_failure_code varchar(80),
  paid_at timestamptz,
  refunded_at timestamptz,
  payment_updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists purchase_orders_customer_created_at_idx
  on public.purchase_orders (customer_id, created_at desc);

create table if not exists public.purchase_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.purchase_orders(id) on delete cascade,
  product_id bigint,
  product_name varchar(180) not null,
  quantity integer not null check (quantity between 1 and 99),
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  shoe_size varchar(20),
  color_variant varchar(60)
);

create table if not exists public.payment_webhook_events (
  id varchar(255) primary key,
  event_type varchar(100) not null,
  object_id varchar(255),
  processed_at timestamptz not null default now()
);

create table if not exists public.payment_checkout_attempts (
  idempotency_key varchar(36) primary key,
  customer_id bigint not null references public.customer_accounts(id),
  request_hash varchar(64) not null,
  order_id bigint references public.purchase_orders(id),
  state varchar(20) not null default 'NEW',
  lease_token varchar(36),
  lease_expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_refunds (
  refund_id varchar(255) primary key,
  order_id bigint not null references public.purchase_orders(id),
  attempt_id varchar(36),
  amount numeric(12, 2) not null check (amount > 0),
  currency varchar(3) not null,
  status varchar(30) not null,
  last_event_created bigint not null,
  last_event_rank integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_disputes (
  dispute_id varchar(255) primary key,
  order_id bigint not null references public.purchase_orders(id),
  amount numeric(12, 2) not null check (amount > 0),
  currency varchar(3) not null,
  status varchar(40) not null,
  last_event_created bigint not null,
  last_event_rank integer not null default 0,
  updated_at timestamptz not null default now()
);

create index if not exists payment_webhook_events_processed_at_idx
  on public.payment_webhook_events (processed_at desc);
create index if not exists payment_refunds_order_idx on public.payment_refunds (order_id);
create index if not exists payment_disputes_order_idx on public.payment_disputes (order_id);
alter table public.payment_checkout_attempts add column if not exists state varchar(20) not null default 'NEW';
alter table public.payment_checkout_attempts add column if not exists lease_token varchar(36);
alter table public.payment_checkout_attempts add column if not exists lease_expires_at timestamptz;

-- Safe upgrades for databases created by older versions of the application.
alter table public.products add column if not exists stock_quantity integer not null default 0;
alter table public.products add column if not exists version bigint not null default 0;
alter table public.products drop constraint if exists products_category_check;
alter table public.purchase_orders add column if not exists external_reference varchar(80);
alter table public.purchase_orders alter column status type varchar(40);
alter table public.purchase_orders add column if not exists payment_state varchar(30) not null default 'PENDING';
alter table public.purchase_orders add column if not exists refund_state varchar(20) not null default 'NONE';
alter table public.purchase_orders add column if not exists dispute_state varchar(20) not null default 'NONE';
alter table public.purchase_orders add column if not exists fulfillment_review_required boolean not null default false;
alter table public.purchase_orders add column if not exists inventory_status varchar(30) not null default 'NONE';
alter table public.purchase_orders add column if not exists payment_provider varchar(20);
alter table public.purchase_orders add column if not exists legacy_payment_reference varchar(600);
alter table public.purchase_orders add column if not exists checkout_session_id varchar(255);
alter table public.purchase_orders add column if not exists checkout_status varchar(20);
alter table public.purchase_orders add column if not exists checkout_url varchar(2048);
alter table public.purchase_orders add column if not exists checkout_request_hash varchar(64);
alter table public.purchase_orders add column if not exists checkout_expires_at timestamptz;
alter table public.purchase_orders add column if not exists provider_success_url varchar(2048);
alter table public.purchase_orders add column if not exists provider_cancel_url varchar(2048);
alter table public.purchase_orders add column if not exists pix_expires_seconds bigint;
alter table public.purchase_orders add column if not exists boleto_expires_days bigint;
alter table public.purchase_orders add column if not exists payment_intent_id varchar(255);
alter table public.purchase_orders add column if not exists captured_amount numeric(12, 2);
alter table public.purchase_orders add column if not exists captured_currency varchar(3);
alter table public.purchase_orders add column if not exists refunded_amount numeric(12, 2) not null default 0;
alter table public.purchase_orders add column if not exists refund_attempt_id varchar(36);
alter table public.purchase_orders add column if not exists refund_attempt_amount numeric(12, 2);
alter table public.purchase_orders
  drop constraint if exists purchase_orders_refund_attempt_amount_valid;
alter table public.purchase_orders
  add constraint purchase_orders_refund_attempt_amount_valid
  check (refund_attempt_amount is null
         or (refund_attempt_amount > 0 and refund_attempt_amount <= total));
alter table public.purchase_orders add column if not exists gateway_refund_id varchar(255);
alter table public.purchase_orders add column if not exists payment_failure_code varchar(80);
alter table public.purchase_orders add column if not exists paid_at timestamptz;
alter table public.purchase_orders add column if not exists refunded_at timestamptz;
alter table public.purchase_orders add column if not exists payment_updated_at timestamptz not null default now();
alter table public.purchase_orders add column if not exists postal_code varchar(8);
alter table public.purchase_orders add column if not exists state varchar(2);
alter table public.purchase_orders add column if not exists city varchar(120);
alter table public.purchase_orders add column if not exists neighborhood varchar(160);
alter table public.purchase_orders add column if not exists street varchar(180);
alter table public.purchase_orders add column if not exists address_number varchar(20);
alter table public.purchase_orders add column if not exists complement varchar(120);
update public.purchase_orders set payment_provider = 'LEGACY' where payment_provider is null;
alter table public.purchase_orders alter column payment_provider set default 'STRIPE';
alter table public.purchase_orders alter column payment_provider set not null;
update public.purchase_orders
  set inventory_status = case when status = 'PAID' then 'COMMITTED' else 'NONE' end
  where inventory_status = 'NONE';

-- Split the historical single status into independent payment/refund/dispute/fulfillment axes.
update public.purchase_orders
set payment_state = case
  when payment_provider = 'LEGACY' and status = 'PAID' then 'REVIEW_REQUIRED'
  when status in ('PAID', 'REFUND_PENDING', 'PARTIALLY_REFUNDED', 'REFUNDED', 'REFUND_FAILED',
                  'DISPUTED', 'DISPUTE_LOST', 'FULFILLMENT_REVIEW_REQUIRED') then 'SUCCEEDED'
  when status = 'PAYMENT_PROCESSING' then 'PROCESSING'
  when status = 'PAYMENT_FAILED' then 'FAILED'
  when status = 'PAYMENT_CANCELED' then 'CANCELED'
  when status = 'PAYMENT_EXPIRED' then 'EXPIRED'
  when status = 'PAYMENT_REVIEW_REQUIRED' then 'REVIEW_REQUIRED'
  else payment_state
end,
refund_state = case
  when status = 'REFUND_PENDING' then 'PENDING'
  when status = 'PARTIALLY_REFUNDED' then 'PARTIAL'
  when status = 'REFUNDED' then 'FULL'
  when status = 'REFUND_FAILED' then 'FAILED'
  else refund_state
end,
dispute_state = case
  when status = 'DISPUTED' then 'OPEN'
  when status = 'DISPUTE_LOST' then 'LOST'
  else dispute_state
end,
fulfillment_review_required = fulfillment_review_required or (status = 'FULFILLMENT_REVIEW_REQUIRED'),
checkout_status = case
  when status in ('PAID', 'REFUND_PENDING', 'PARTIALLY_REFUNDED', 'REFUNDED', 'REFUND_FAILED',
                  'DISPUTED', 'DISPUTE_LOST', 'FULFILLMENT_REVIEW_REQUIRED') then 'complete'
  when status in ('PAYMENT_CANCELED', 'PAYMENT_EXPIRED') then 'expired'
  else checkout_status
end;

-- The retired provider never supplied enough trusted data to backfill captured_amount/currency.
-- Keep its identifiers for reconciliation and surface historical PAID rows for manual review.
update public.purchase_orders
set status = 'PAYMENT_REVIEW_REQUIRED'
where payment_provider = 'LEGACY' and status = 'PAID';
drop index if exists public.purchase_orders_payment_preference_unique;
drop index if exists public.purchase_orders_gateway_payment_unique;

-- Preserve identifiers from the retired integration under a provider-neutral audit field.
do $migration$
begin
  if exists (select 1 from information_schema.columns
             where table_schema = 'public' and table_name = 'purchase_orders'
               and column_name = 'payment_preference_id') then
    execute $sql$
      update public.purchase_orders
      set legacy_payment_reference = concat_ws('|', nullif(legacy_payment_reference, ''),
        nullif(payment_preference_id::text, ''))
      where payment_preference_id is not null
    $sql$;
  end if;
  if exists (select 1 from information_schema.columns
             where table_schema = 'public' and table_name = 'purchase_orders'
               and column_name = 'gateway_payment_id') then
    execute $sql$
      update public.purchase_orders
      set legacy_payment_reference = concat_ws('|', nullif(legacy_payment_reference, ''),
        nullif(gateway_payment_id::text, ''))
      where gateway_payment_id is not null
    $sql$;
  end if;
end
$migration$;

alter table public.purchase_orders drop column if exists payment_preference_id;
alter table public.purchase_orders drop column if exists gateway_payment_id;
alter table public.purchase_orders drop column if exists dispute_open;
alter table public.purchase_orders drop column if exists dispute_event_created;
alter table public.purchase_orders drop column if exists dispute_event_rank;
create unique index if not exists purchase_orders_external_reference_unique on public.purchase_orders (external_reference) where external_reference is not null;
create unique index if not exists purchase_orders_checkout_session_unique on public.purchase_orders (checkout_session_id) where checkout_session_id is not null;
create unique index if not exists purchase_orders_payment_intent_unique on public.purchase_orders (payment_intent_id) where payment_intent_id is not null;

-- WhatsApp payment provider support (idempotent upgrades).
alter table public.purchase_orders add column if not exists whatsapp_url varchar(2048);
alter table public.purchase_orders add column if not exists whatsapp_expires_at timestamptz;

-- Extend the payment_provider CHECK constraint to accept WHATSAPP orders.
-- We drop and recreate so re-execution on an already-migrated schema is safe.
alter table public.purchase_orders
  drop constraint if exists purchase_orders_payment_provider_check;
alter table public.purchase_orders
  add constraint purchase_orders_payment_provider_check
  check (payment_provider in ('STRIPE', 'LEGACY', 'WHATSAPP'));

-- Partial index used by the WhatsApp order expiry cleanup job.
create index if not exists purchase_orders_whatsapp_expiry_idx
  on public.purchase_orders (whatsapp_expires_at)
  where payment_provider = 'WHATSAPP' and payment_state = 'PENDING';

-- Store reviews (Verified buyers only)
create table if not exists public.store_reviews (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customer_accounts(id) on delete cascade,
  author_name varchar(160) not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment varchar(4000) not null,
  created_at timestamptz not null default now()
);

create index if not exists store_reviews_created_at_idx
  on public.store_reviews (created_at desc);

-- Sneaker Product reviews (Verified buyers of that specific shoe)
create table if not exists public.product_reviews (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customer_accounts(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  author_name varchar(160) not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment varchar(4000) not null,
  created_at timestamptz not null default now()
);

create index if not exists product_reviews_product_created_at_idx
  on public.product_reviews (product_id, created_at desc);

-- Customer Support Messages & FAQ Inquiries (SAC)
create table if not exists public.support_messages (
  id bigint generated by default as identity primary key,
  full_name varchar(160) not null,
  email varchar(254) not null,
  subject varchar(200) not null,
  message varchar(4000) not null,
  status varchar(20) not null default 'PENDING',
  created_at timestamptz not null default now()
);

create index if not exists support_messages_created_at_idx
  on public.support_messages (created_at desc);

-- Discount Coupons
create table if not exists public.discount_coupons (
  id bigint generated by default as identity primary key,
  code varchar(40) not null unique,
  discount_percent numeric(5,2),
  discount_amount numeric(12,2),
  min_order_value numeric(12,2) default 0,
  max_uses integer,
  used_count integer not null default 0,
  expires_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Back-in-Stock Alerts
create table if not exists public.stock_alerts (
  id bigint generated by default as identity primary key,
  product_id bigint not null,
  product_name varchar(200) not null,
  size varchar(20) not null,
  color varchar(80) not null,
  email varchar(254) not null,
  whatsapp varchar(30),
  status varchar(20) not null default 'PENDING',
  created_at timestamptz not null default now()
);

create index if not exists stock_alerts_product_id_idx
  on public.stock_alerts (product_id, status);

-- Storefront Footer Settings (100% customizable from backend)
create table if not exists public.storefront_footer_settings (
  id integer primary key default 1,
  wordmark varchar(100) not null default 'KICKS STORE',
  brand_tagline varchar(255) not null default 'Calce a felicidade. Viva o seu ritmo.',
  location_title varchar(100) not null default '',
  address_line1 varchar(255) not null default '',
  address_line2 varchar(255) not null default '',
  hours_title varchar(100) not null default '',
  store_hours_line1 varchar(255) not null default '',
  store_hours_line2 varchar(255) not null default '',
  auth_title varchar(100) not null default '',
  auth_badge_title varchar(255) not null default '',
  auth_badge_detail varchar(255) not null default '',
  nav_title varchar(100) not null default '',
  back_to_top_text varchar(100) not null default '',
  contact_email varchar(254) not null default '',
  contact_phone varchar(100) not null default '',
  cnpj_text varchar(100) not null default '',
  instagram_handle varchar(100) not null default '',
  cities_rail varchar(255) not null default '',
  copyright_text varchar(255) not null default 'Todos os direitos reservados.',
  version bigint not null default 0,
  constraint storefront_footer_settings_singleton_check check (id = 1)
);

-- Keep database defaults truthful when this script upgrades an existing installation.
alter table public.storefront_footer_settings alter column brand_tagline set default 'Calce a felicidade. Viva o seu ritmo.';
alter table public.storefront_footer_settings alter column location_title set default '';
alter table public.storefront_footer_settings alter column address_line1 set default '';
alter table public.storefront_footer_settings alter column address_line2 set default '';
alter table public.storefront_footer_settings alter column hours_title set default '';
alter table public.storefront_footer_settings alter column store_hours_line1 set default '';
alter table public.storefront_footer_settings alter column store_hours_line2 set default '';
alter table public.storefront_footer_settings alter column auth_title set default '';
alter table public.storefront_footer_settings alter column auth_badge_title set default '';
alter table public.storefront_footer_settings alter column auth_badge_detail set default '';
alter table public.storefront_footer_settings alter column nav_title set default '';
alter table public.storefront_footer_settings alter column back_to_top_text set default '';
alter table public.storefront_footer_settings alter column contact_email set default '';
alter table public.storefront_footer_settings alter column contact_phone set default '';
alter table public.storefront_footer_settings alter column cnpj_text set default '';
alter table public.storefront_footer_settings alter column instagram_handle set default '';
alter table public.storefront_footer_settings alter column cities_rail set default '';
alter table public.storefront_footer_settings alter column copyright_text set default 'Todos os direitos reservados.';

insert into public.storefront_footer_settings (id, version)
values (1, 0)
on conflict (id) do nothing;

-- Remove only the exact legacy placeholders; preserve every administrator-defined value.
update public.storefront_footer_settings
set brand_tagline = case when brand_tagline = 'THE DEFINITIVE SNEAKER CULTURE EXPERIENCE' then 'Calce a felicidade. Viva o seu ritmo.' else brand_tagline end,
    location_title = case when location_title = 'LOCALIZAÇÃO' then '' else location_title end,
    address_line1 = case when address_line1 = 'Rua Oscar Freire, 1024' then '' else address_line1 end,
    address_line2 = case when address_line2 = 'Jardins • São Paulo, SP' then '' else address_line2 end,
    hours_title = case when hours_title = 'HORÁRIO DE ATENDIMENTO' then '' else hours_title end,
    store_hours_line1 = case when store_hours_line1 = 'Seg - Sáb: 10h às 20h' then '' else store_hours_line1 end,
    store_hours_line2 = case when store_hours_line2 = 'Domingos: 12h às 18h' then '' else store_hours_line2 end,
    auth_title = case when auth_title = 'GARANTIA DE AUTENTICIDADE' then '' else auth_title end,
    auth_badge_title = case when auth_badge_title = 'Autenticação Física 100%' then '' else auth_badge_title end,
    auth_badge_detail = case when auth_badge_detail = 'Lacre de Segurança Blindado' then '' else auth_badge_detail end,
    nav_title = case when nav_title = 'NAVEGAÇÃO' then '' else nav_title end,
    back_to_top_text = case when back_to_top_text = 'Voltar ao Topo ↑' then '' else back_to_top_text end,
    contact_email = case when contact_email = 'contato@kicksstore.com.br' then '' else contact_email end,
    contact_phone = case when contact_phone = '(11) 99152-6318' then '' else contact_phone end,
    cnpj_text = case when cnpj_text = 'CNPJ: 12.345.678/0001-90' then '' else cnpj_text end,
    instagram_handle = case when instagram_handle = '@kicksstore_oficial' then '' else instagram_handle end,
    cities_rail = case when cities_rail = 'TOKYO • SÃO PAULO • NEW YORK • LONDON' then '' else cities_rail end,
    copyright_text = case when copyright_text = 'TODOS OS DIREITOS RESERVADOS.' then 'Todos os direitos reservados.' else copyright_text end
where id = 1;

-- The browser never talks to Supabase directly. Keep PII and password hashes outside the Data API.
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.storefront_hero_settings enable row level security;
alter table public.storefront_hero_images enable row level security;
alter table public.storefront_footer_settings enable row level security;
alter table public.customer_accounts enable row level security;
alter table public.customer_addresses enable row level security;
alter table public.purchase_orders enable row level security;
alter table public.purchase_order_items enable row level security;
alter table public.store_reviews enable row level security;
alter table public.product_reviews enable row level security;
alter table public.support_messages enable row level security;
alter table public.discount_coupons enable row level security;
alter table public.stock_alerts enable row level security;
alter table public.payment_webhook_events enable row level security;
alter table public.payment_checkout_attempts enable row level security;
alter table public.payment_refunds enable row level security;
alter table public.payment_disputes enable row level security;
revoke all on table public.products, public.product_images,
  public.storefront_hero_settings, public.storefront_hero_images,
  public.storefront_footer_settings,
  public.customer_accounts, public.customer_addresses, public.purchase_orders,
  public.purchase_order_items, public.store_reviews, public.product_reviews,
  public.support_messages, public.discount_coupons, public.stock_alerts,
  public.payment_webhook_events, public.payment_checkout_attempts,
  public.payment_refunds, public.payment_disputes from anon, authenticated;
revoke all on sequence public.products_id_seq, public.product_images_id_seq,
  public.storefront_hero_images_id_seq, public.customer_accounts_id_seq,
  public.customer_addresses_id_seq, public.purchase_orders_id_seq,
  public.purchase_order_items_id_seq, public.support_messages_id_seq,
  public.discount_coupons_id_seq, public.stock_alerts_id_seq from anon, authenticated;

