package com.ecommerce.hardware.model;

public enum PaymentStatus {
    PENDING_PAYMENT,
    PAYMENT_PROCESSING,
    PAID,
    PAYMENT_FAILED,
    PAYMENT_CANCELED,
    PAYMENT_EXPIRED,
    REFUND_PENDING,
    PARTIALLY_REFUNDED,
    REFUNDED,
    REFUND_FAILED,
    DISPUTED,
    DISPUTE_LOST,
    PAYMENT_REVIEW_REQUIRED,
    FULFILLMENT_REVIEW_REQUIRED
}
