import nexusObjectsHero from './assets/brand/nexus-objects-hero.png';

export const STORE_THEMES = {
  hardware: {
    id: 'hardware',
    name: 'Nexus Atelier',
    shortName: 'N',
    category: 'Objetos e tecnologia',
    eyebrow: 'Edição 01 · tecnologia para viver melhor',
    title: 'Objetos para um cotidiano mais interessante.',
    description: 'Uma curadoria de tecnologia, matéria e forma para espaços que têm personalidade própria.',
    collectionLabel: 'Peças que fazem sentido',
    productLabel: 'Curadoria Nexus',
    cta: 'Ver a seleção',
    stat: 'Envio rápido para todo o Brasil',
    image: nexusObjectsHero,
    imageAlt: 'Objetos tecnológicos em uma composição editorial escura',
    stickerLabel: 'edição 01',
    heroNote: 'Matéria, luz e função',
    heroDetail: 'Uma seleção para usar todos os dias.',
    chips: ['Design durável', 'Compra protegida', 'Novidades selecionadas'],
    motif: 'grid',
  },
  sneakers: {
    id: 'sneakers',
    name: 'Passo Livre',
    shortName: 'P',
    category: 'Tênis',
    eyebrow: 'Drop da semana · feito para ir longe',
    title: 'O ritmo da rua, do seu jeito.',
    description: 'Tênis de presença, conforto de verdade e cores que não passam despercebidas.',
    collectionLabel: 'Escolhas que caminham com você',
    productLabel: 'Drop especial',
    cta: 'Encontrar meu par',
    stat: 'Troca fácil em até 30 dias',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1400&q=88',
    imageAlt: 'Tênis vermelho em um fundo azul profundo',
    stickerLabel: 'novo drop',
    heroNote: 'Feito para movimento',
    heroDetail: 'Pares que acompanham a sua próxima história.',
    chips: ['Conforto absoluto', 'Drops exclusivos', 'Frete para todo o Brasil'],
    motif: 'motion',
  },
  tarts: {
    id: 'tarts',
    name: 'Doce Pedaço',
    shortName: 'D',
    category: 'Tortinha',
    eyebrow: 'Feito hoje · para saborear sem pressa',
    title: 'Pequenos rituais, grandes sabores.',
    description: 'Tortinhas artesanais, ingredientes gentis e aquele detalhe que muda a tarde inteira.',
    collectionLabel: 'Feitas hoje, para adoçar agora',
    productLabel: 'Feito à mão',
    cta: 'Escolher tortinhas',
    stat: 'Produção fresca todos os dias',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1400&q=88',
    imageAlt: 'Tortinhas e doces em uma composição delicada',
    stickerLabel: 'feito hoje',
    heroNote: 'Receitas de vitrine',
    heroDetail: 'Carinho que se vê antes da primeira mordida.',
    chips: ['Massa artesanal', 'Ingredientes frescos', 'Entrega com carinho'],
    motif: 'petals',
  },
};
