export const STORE_THEME = {
  id: 'sneakers',
  name: 'Kicks Store',
  category: 'Tênis',
  eyebrow: 'Drop da semana · feito para ir longe',
  title: 'O ritmo da rua, do seu jeito.',
  titleLead: 'O ritmo da rua,',
  titleAccent: 'do seu jeito.',
  description: 'Tênis de presença, conforto de verdade e cores que não passam despercebidas.',
  collectionLabel: 'Escolhas que caminham com você',
  productLabel: 'Drop especial',
  cta: 'Encontrar meu par',
  stat: 'Troca fácil em até 30 dias',
  image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1400&q=88',
  imageAlt: 'Tênis vermelho em um fundo azul profundo',
  stickerLabel: 'novo drop',
  heroNote: 'Feito para movimento',
  heroDetail: 'Pares que acompanham a sua próxima história.',
  edition: 'DROP / 07',
  rail: 'Rua, pista e movimento · Brasil',
  footerStatement: 'Pares com presença para histórias que ainda não pararam de andar.',
  themeColor: '#ebe7de',
  proofs: [
    { mark: '30', label: 'Troca sem drama', detail: 'Até 30 dias para decidir' },
    { mark: '→', label: 'Despacho rápido', detail: 'Seu par entra logo em movimento' },
    { mark: '∞', label: 'Conforto real', detail: 'Escolhas para o dia inteiro' },
  ],
  chips: ['Conforto absoluto', 'Drops exclusivos', 'Frete para todo o Brasil'],
};
